# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20160124_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
    ]
